
# Supabase configuration file
project_id = "7379eb6cfd6f990050453626e4ae34f103f5e484daa63e9a4a448e07b6aed210"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[functions.send-order-sms]
verify_jwt = false

[storage]
enabled = true
port = 54326
file_size_limit = "50MiB"
features = {
  image_transformation = true,
  duplicate_protection = false
}

[auth]
enabled = true
port = 54327
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_email_change_confirmations = true
enable_phone_confirmations = false
enable_phone_change_confirmations = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }}"

[[auth.providers.email]]
enabled = true
default_audience = "authenticated"

[[auth.providers.phone]]
enabled = false
default_audience = "authenticated"

[edge_runtime]
enabled = true
port = 54328

[analytics]
enabled = false
port = 54329
vector_port = 54330
gw_port = 54331
