// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdswnywedlagrukfyxzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpkc3dueXdlZGxhZ3J1a2Z5eHprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTg3MjUsImV4cCI6MjA2MzgzNDcyNX0.GKNkc87CYz8HAytqhcitTa4K5dh-sjfy5Wo1mXCy31w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);